# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b721e20ccc9e902279f1cfa6fb9cee68aa265be7b0957f58f284f52f1223fa0d4f710b8fbb6bf127fcd74dd84e615579513069f7986c7050bf9b1194034433c0

test:
  secret_key_base: 961a4744f5019cd76f0cb4a9ef54fbafdf2754c845c52a96ec01ffadc6802a628b4f0faba2b0b417e7e20910c2c075fe8d51cec146b78c646c58d275ab4d78ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
